# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Inject preset values for research methods

ResearchMethod.create([{method_name: 'Case Study', method_status: 1},
                       {method_name: 'Field Observation', method_status: 1},
                       {method_name: 'Experiment', method_status: 1},
                       {method_name: 'Interview', method_status: 1},
                       {method_name: 'Survey', method_status: 1}])
# Inject preset values for research participants
Participant.create([{participate_name: 'undergraduate students'},
                    {participate_name: 'postgraduate students'},
                    {participate_name: 'practitioners'}])
# Inject preset values for Methodologies
Methodology.create([{methodology_name: 'Scrum', description: 'Description'},
                    {methodology_name: 'Waterfall', description: 'Description'},
                    {methodology_name: 'Spiral', description: 'Description'},
                    {methodology_name: 'XP', description: 'Description'},
                    {methodology_name: 'Rational Unified Process', description: 'Description'},
                    {methodology_name: 'Crystal', description: 'Description'},
                    {methodology_name: 'Clean room', description: 'Description'},
                    {methodology_name: 'Feature Driven Development', description: 'Description'},
                    {methodology_name: 'Model Driven Development', description: 'Description'},
                    {methodology_name: 'Domain Driven Development', description: 'Description'},
                    {methodology_name: 'Formal methods', description: 'Description'},
                    {methodology_name: 'Problem Driven Development', description: 'Description'},
                    {methodology_name: 'Cloud computing', description: 'Description'},
                    {methodology_name: 'Service Oriented Development', description: 'Description'},
                    {methodology_name: 'Aspect Oriented Development', description: 'Description'},
                    {methodology_name: 'Valuse Driven Development', description: 'Description'},
                    {methodology_name: 'Product Driven Development', description: 'Description'},
                    {methodology_name: 'Agile', description: 'Description'},])

SeMethod.create([
  {method_name: 'TDD', method_description: 'se-method-description'},
  {method_name: 'BDD', method_description: 'se-method-description'},
  {method_name: 'pair programming', method_description: 'se-method-description'},
  {method_name: 'planning poker', method_description: 'se-method-description'},
  {method_name: 'daily standu meetings', method_description: 'se-method-description'},
  {method_name: 'story boards', method_description: 'se-method-description'},
  {method_name: 'user story mapping', method_description: 'se-method-description'},
  {method_name: 'continuous integration', method_description: 'se-method-description'},
  {method_name: 'retrospectives', method_description: 'se-method-description'},
  {method_name: 'burn down charts', method_description: 'se-method-description'},
  {method_name: 'requirements prioritisation', method_description: 'se-method-description'},
  {method_name: 'version control', method_description: 'se-method-description'},
  {method_name: 'code sharing', method_description: 'se-method-description'},
  ])

User.create!([
  {
    email: "nobody@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 0,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname", 
  },
  {
    email: "user@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 1,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname",
  },
  {
    email: "moderator@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 2,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname",
  },
  {
    email: "analyst@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 4,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname",
  },
  {
    email: "admin@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 8,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname",
  },
  {
    email: "super@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 15,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname",
  },
  {
    email: "3@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 3,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname",
  },
  {
    email: "5@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 5,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname",
  },
  {
    email: "7@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 7,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname",
  },
  {
    email: "9@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 9,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname",
  },
  {
    email: "11@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 11,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname",
  },
  {
    email: "13@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 13,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname",
  },
  {
    email: "14@example.com", password: "123456", password_confirmation: "123456",
    reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", roles_mask: 14,
    first_name: "Fistname", middle_name: "no-middle-name", last_name: "Lastname",
  },
])

#status,submitter_id,title,source_title,category,publisher,rating_tenth,
# published_time,year,volume_number,issue_number,page_str,page_begin,page_cease

EvidenceSource.create([
  {
    status: 'NEW', submitter_id: 1,
    title: 'From CMMI and Isolation to Scrum, Agile, Lean and Collaboration',
    source_title: 'Agile Conference, 2009. AGILE \'09.',
    year: 2009, volume_number: 33, issue_number: 4,
    page_str: '283-288', page_begin: 283, page_cease: 288,
    DOI: '10.1109/AGILE.2009.18',
    category: 'Academic Journals',
    publisher: 'Elsevier Inc',
    published_time: DateTime.new(2009,10,01),
    rating_tenth: 10,
    research_aim: 'Money',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'Distributed Scrum: Agile Project Management with Outsourced Development Teams',
    source_title: 'System Sciences, 2007. HICSS 2007. 40th Annual Hawaii International Conference on',
    year: 2007, volume_number: nil, issue_number: nil,
    page_str: '274a-274a', page_begin: 274, page_cease: 274,
    DOI: '10.1109/HICSS.2007.180',
    category: 'Academic Journals',
    publisher: 'AUT',
    published_time: DateTime.new(2007,10,01),
    rating_tenth: 10,
    research_aim: 'Money',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'The Effectiveness of Pair Programming: Software Professionals\' Perceptions',
    source_title: 'IEEE Software',
    year: 2016, volume_number: 33, issue_number: 4,
    page_str: '72-79', page_begin: 72, page_cease: 79,
    DOI: '10.1109/MS.2015.106',
    category: 'Magagines',
    publisher: 'Apple',
    published_time: DateTime.new(2006,01,01),
    rating_tenth: 10,
    research_aim: 'Money',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'A study of pair-programming configuration for learning computer networks',
    source_title: 'Ubi-Media Computing (UMEDIA), 2015 8th International Conference on',
    year: 2015, volume_number: nil, issue_number: nil,
    page_str: '369-375', page_begin: 369, page_cease: 375,
    DOI: '10.1109/UMEDIA.2015.7297488',
    category: 'Magagines',
    publisher: 'New Zealand',
    published_time: DateTime.new(2015,01,01),
    rating_tenth: 2,
    research_aim: 'Money',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'Qualitative Analysis of Knowledge Transfer in Pair Programming',
    source_title: '2015 IEEE/ACM 37th IEEE International Conference on Software Engineering',
    year: 2015, volume_number: nil, issue_number: nil,
    page_str: '855-858', page_begin: 855, page_cease: 858,
    DOI: '10.1109/ICSE.2015.277',
    category: 'Magagines',
    publisher: 'Apple',
    published_time: DateTime.new(2015,01,01),
    rating_tenth: 10,
    research_aim: 'Money',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'How to Live',
    source_title: 'System Sciences, 2007',
    year: 2106, volume_number: nil, issue_number: nil,
    page_str: '274a-274a', page_begin: 274, page_cease: 274,
    DOI: '10.1109/SSSSS.2007.180',
    category: 'eBook',
    publisher: 'AUT',
    published_time: DateTime.new(2016,10,01),
    rating_tenth: 10,
    research_aim: 'Business',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'How to love',
    source_title: 'measuring well-being',
    year: 1999, volume_number: nil, issue_number: nil,
    page_str: '274a-274a', page_begin: 274, page_cease: 274,
    DOI: '10.1109/FFFF.2007.180',
    category: 'Academic Journals',
    publisher: 'AUT',
    published_time: DateTime.new(1999,10,01),
    rating_tenth: 3,
    research_aim: 'Money',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'What to love',
    source_title: 'measuring well-being',
    year: 2014, volume_number: 100, issue_number: 3,
    page_str: '274a-274a', page_begin: 100, page_cease: 100,
    DOI: '10.1109/HICSS.2007.180',
    category: 'News',
    publisher: 'Apple',
    published_time: DateTime.new(2014,10,01),
    rating_tenth: 3,
    research_aim: 'Education',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'FP-Hadoop: Efficient processing of skewed MapReduce jobs',
    source_title: 'In Information Systems August-September 2010 60:69-84',
    year: 2010, volume_number: 100, issue_number: 3,
    page_str: '274a-274a', page_begin: 100, page_cease: 100,
    DOI: '10.1109/SSSS.2007.180',
    category: 'Academic Journals',
    publisher: 'Elsevier Ltd',
    published_time: DateTime.new(2010,02,01),
    rating_tenth: 4,
    research_aim: 'Education',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'MapReduce jobs',
    source_title: 'In Information Systems August-September 1999 60:69-84',
    year: 1999, volume_number: 100, issue_number: 3,
    page_str: '274a-274a', page_begin: 100, page_cease: 100,
    DOI: '10.1109/FFFF.2007.180',
    category: 'Academic Journals',
    publisher: 'Elsevier Ltd',
    published_time: DateTime.new(1999,02,01),
    rating_tenth: 4,
    research_aim: 'Education',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'FP-Hadoop: Efficient processing of skewed MapReduce jobs',
    source_title: 'In Information Systems August-September 2016 60:69-84',
    year: 2010, volume_number: 100, issue_number: 3,
    page_str: '274a-274a', page_begin: 100, page_cease: 100,
    DOI: '10.1109/ABCD.2007.180',
    category: 'Academic Journals',
    publisher: 'Elsevier Ltd',
    published_time: DateTime.new(2010,02,01),
    rating_tenth: 9,
    research_aim: 'Education',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'IOS VS Android',
    source_title: 'Communications of the ACM. Apr2006, Vol. 58 Issue 4, p46-55. 10p. 1 Color Photograph, 2 Diagrams, 8 Charts, 6 Graph',
    year: 2006, volume_number: 100, issue_number: 3,
    page_str: '274a-274a', page_begin: 100, page_cease: 100,
    DOI: '10.1109/FFFF.2007.180',
    category: 'News',
    publisher: 'Google',
    published_time: DateTime.new(2006,12,25),
    rating_tenth: 9,
    research_aim: 'Ad.',
  },

  {
    status: 'NEW', submitter_id: 1,
    title: 'IOS VS Android2',
    source_title: 'Communications of the ACM. iagrams, 8 Charts, 6 Graph',
    year: 2014, volume_number: 100, issue_number: 3,
    page_str: '274a-274a', page_begin: 100, page_cease: 100,
    DOI: '10.1109/FFFF.2014.180',
    category: 'News',
    publisher: 'Google',
    published_time: DateTime.new(2014,12,25),
    rating_tenth: 9,
    research_aim: 'Ad.',
  },

  {
    status: 'NEW', submitter_id: 1,
    title: 'Stop Studying',
    source_title: 'Communications of the ACM.',
    year: 2001, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.11029/FFFF.2007.180',
    category: 'News',
    publisher: 'Google',
    published_time: DateTime.new(2001,12,25),
    rating_tenth: 9,
    research_aim: 'Education',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'GOM-Hadoop: A distributed framework for efficient analytics on ordered datasets',
    source_title: 'In Journal of Parallel and Distributed Computing September 2015 83:58-69',
    year: 2015, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.1016/j.jpdc.2015.05.003',
    category: 'Article',
    publisher: 'Elsevier Inc.',
    published_time: DateTime.new(2015,12,25),
    rating_tenth: 9,
    research_aim: 'Education',
  },
  {
    status: 'NEW', submitter_id: 1,
    title: 'OBJC What is problem?',
    source_title: 'Communications of the Orable. ',
    year: 1988, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.11029/FFFF.1988.180',
    category: 'News',
    publisher: 'Oracle',
    published_time: DateTime.new(1988,12,12),
    rating_tenth: 9,
    research_aim: 'Education',
  },

  {
    status: 'NEW', submitter_id: 1,
    title: 'IPhone secrets : do what you never thought possible with your iPhone',
    source_title: 'Indianapolis, IN : John Wiley & Sons, [2013]',
    year: 2013, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.11029/FFFF.2013.180',
    category: 'Books',
    publisher: 'Shaomi',
    published_time: DateTime.new(2013,1,1),
    rating_tenth: 9,
    research_aim: 'Education',
  },

  {
    status: 'NEW', submitter_id: 1,
    title: 'How to eat',
    source_title: 'Apple and Computer',
    year: 1921, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.11029/FFFF.1921.180',
    category: 'News',
    publisher: 'IMF',
    published_time: DateTime.new(1921,12,12),
    rating_tenth: 9,
    research_aim: 'Education',
  },


  {
    status: 'NEW', submitter_id: 1,
    title: 'Why id Eve eat apple?',
    source_title: 'Haven',
    year: 1899, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.11029/FFFF.1899.180',
    category: 'Books',
    publisher: 'Oracle',
    published_time: DateTime.new(1899,12,25),
    rating_tenth: 9,
    research_aim: 'Education',
  },


  {
    status: 'NEW', submitter_id: 1,
    title: 'OBJC What is problem2?',
    source_title: 'ACE Communications of the Orable. ',
    year: 2006, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.11029/FFFF.1988.180',
    category: 'eBooks',
    publisher: 'aOracle',
    published_time: DateTime.new(2006,12,12),
    rating_tenth: 9,
    research_aim: 'Education',
  },


  {
    status: 'NEW', submitter_id: 1,
    title: 'OBJC What is problem?:second edition',
    source_title: 'Communications of the Orable. ',
    year: 2016, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.11029/FFFF.2016.2016',
    category: 'News',
    publisher: 'Oracle',
    published_time: DateTime.new(2016,12,12),
    rating_tenth: 1,
    research_aim: 'Education',
  },


  {
    status: 'NEW', submitter_id: 1,
    title: 'OBJC What is problem third?',
    source_title: 'Communications of the Orable. ',
    year: 2016, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.11029/FFFF.1988.180',
    category: 'News',
    publisher: 'Oracle',
    published_time: DateTime.new(2016,12,25),
    rating_tenth: 9,
    research_aim: 'Education',
  },


  {
    status: 'NEW', submitter_id: 1,
    title: 'OBJC What is problem?',
    source_title: 'Communications of the Orable. ',
    year: 1988, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.2016/FFFF.2016.180',
    category: 'News',
    publisher: 'Oracle',
    published_time: DateTime.new(1988,12,12),
    rating_tenth: 9,
    research_aim: 'Education',
  },


  {
    status: 'NEW', submitter_id: 1,
    title: 'North Korea power',
    source_title: 'Cold War',
    year: 1970, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.11029/FFFF.1988.180',
    category: 'Reports',
    publisher: 'Pengyang',
    published_time: DateTime.new(1970,12,12),
    rating_tenth: 9,
    research_aim: 'Ad.',
  },


  {
    status: 'NEW', submitter_id: 1,
    title: 'Human resource',
    source_title: 'Communications of Animal',
    year: 1921, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.11029/FFFF.1988.180',
    category: 'Books',
    publisher: 'Atlanta, Ga. : Big Nerd Ranch, [2010]',
    published_time: DateTime.new(1921,12,12),
    rating_tenth: 9,
    research_aim: 'Education',
  },

  {
    status: 'NEW', submitter_id: 1,
    title: 'resource Human',
    source_title: 'Communications of Animal',
    year: 1922, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.11029/FFFF.1922.180',
    category: 'Books',
    publisher: 'Atlanta, Ga. : Big Nerd Ranch, [1922]',
    published_time: DateTime.new(1922,12,12),
    rating_tenth: 9,
    research_aim: 'Education',
  },

  {
    status: 'NEW', submitter_id: 1,
    title: 'How Colors in Business Dashboards Affect Users Decision Making.',
    source_title: 'ommunications of the ACM. Apr2016, Vol. 59 Issue 4, p50-57. 8p. 1 Color Photograph, 4 Charts, 6 Graphs.',
    year: 2008, volume_number: 100, issue_number: 4,
    page_str: '274a-274a', page_begin: 100, page_cease: 300,
    DOI: '10.1145/2818993',
    category: 'Books',
    publisher: 'Atlanta, Ga. : Big Nerd Ranch, [1922]',
    published_time: DateTime.new(2008,12,12),
    rating_tenth: 9,
    research_aim: 'Ads.',
  },
])


EvidenceSourceAuthor.create([
  {evidence_source_id:1, name: 'Shun Yang', name_abbr: 'Dr.K'},
  {evidence_source_id:1, name: 'Emma', name_abbr: 'Dr.J'},
  {evidence_source_id:2, name: 'Shun Yang', name_abbr: 'Dr.K'},
  {evidence_source_id:2, name: 'Emma', name_abbr: 'Dr.J'},
  {evidence_source_id:3, name: 'Shun Yang', name_abbr: 'Dr.K'},
  {evidence_source_id:3, name: 'Emma', name_abbr: 'Dr.J'},

  {evidence_source_id:4, name: 'Steven Jobs', name_abbr: 'SJ'},
  {evidence_source_id:5, name: 'Steven Jobs', name_abbr: 'SJ'},
  {evidence_source_id:6, name: 'Mun Jae In', name_abbr: 'Pre.'},
  {evidence_source_id:8, name: 'Paul Hamilton', name_abbr: 'PH'},
  {evidence_source_id:9, name: 'Paul Hamilton', name_abbr: 'PH'},
  {evidence_source_id:10, name: 'David Joe', name_abbr: 'DJ'},
  {evidence_source_id:11, name: 'David Joe', name_abbr: 'DJ'},
  {evidence_source_id:12, name: 'David Joe', name_abbr: 'DJ'},
  {evidence_source_id:13, name: 'David Joe', name_abbr: 'DJ'},
  {evidence_source_id:14, name: 'David Joe', name_abbr: 'DJ'},
  {evidence_source_id:15, name: 'David Joe', name_abbr: 'DJ'},
  {evidence_source_id:16, name: 'J. K. Rowling', name_abbr: 'JK'},
  {evidence_source_id:17, name: 'J. K. Rowling', name_abbr: 'JK'},
  {evidence_source_id:18, name: 'J. K. Rowling', name_abbr: 'JK'},
  {evidence_source_id:19, name: 'J. K. Rowling', name_abbr: 'JK'},
  {evidence_source_id:20, name: 'J. K. Rowling', name_abbr: 'JK'},
  {evidence_source_id:21, name: 'J. K. Rowling', name_abbr: 'JK'},
  {evidence_source_id:22, name: 'J. K. Rowling', name_abbr: 'JK'},
  {evidence_source_id:23, name: 'J. K. Rowling', name_abbr: 'JK'},
  {evidence_source_id:24, name: 'J. K. Rowling', name_abbr: 'JK'},
  {evidence_source_id:25, name: 'J. K. Rowling', name_abbr: 'JK'},
  {evidence_source_id:26, name: 'Robert King', name_abbr: 'RK'},
  {evidence_source_id:27, name: 'Robert King', name_abbr: 'RK'},
])
